<?php

$ap_configuration_defaults = json_decode('{

  "ArtPress": {
    "color" : "#ecf4f4",
    "base-font-size" : "16",
    "#access__a:link, a:visited__color" : "3",
    "body__a:link, a:visited__color" : "3",
    "body____font-size" : "2",
    "#header__#site-title a:link, #site-title a:visited__font-size" : "5",
    "#header____color" : "3",
    "body__#breadcrumbs li a, #breadcrumbs li__color" : "3",
    "color__2" : "#424242",
    "color__3" : "#528988",
    "color__4" : "#bbbbbb",
    "color__5" : "#fafafa",
    "body__#breadcrumbs li a, #breadcrumbs li__font-size" : "1",
    "body__#breadcrumbs li a, #breadcrumbs li__text-transform" : "2",
    "#access__ul.sub-menu, ul.sub-menu a:link, ul.sub-menu a:visited__background-color" : "5",
    "#access__ul.sub-menu, ul.sub-menu a:link, ul.sub-menu a:visited__color" : "3",
    "body____color" : "2",
    "#header__#site-description__margin-bottom" : "1em",
    "body__#breadcrumbs li a, #breadcrumbs li__margin-bottom" : "2em",
    "body__h4__text-transform" : "2",
    "body__h4__color" : "3",
    "body__.page-title, h1__font-size" : "4",
    "body__h2__font-weight" : "2",
    "body__h2__font-size" : "3",
    "body__h3__font-weight" : "2",
    ".sidebar____background-color" : "1",
    ".sidebar____padding-top" : "0.01em",
    ".sidebar____padding-right" : "1em",
    ".sidebar____padding-bottom" : "1em",
    ".sidebar____padding-left" : "1em",
    ".sidebar____border-radius" : "1em",
    "body__#breadcrumbs li a, #breadcrumbs li__text-decoration" : "1",
    "body__#breadcrumbs li a:hover, #breadcrumbs li a:active__text-decoration" : "2",
    "#header__#site-description__color" : "4",
    "#header____border-bottom-color" : "1",
    "#header____border-bottom-style" : "5",
    "#header____border-bottom-width" : "1px",
    "body__#breadcrumbs li a, #breadcrumbs li__margin-top" : "1em",
    "#footer____border-top-color" : "1",
    "#footer____border-top-style" : "5",
    "#footer____border-top-width" : "1px",
    "body____background-color" : "5",
    "#header__#site-title a:link, #site-title a:visited__text-shadow__horizontal" : "1px",
    "#header__#site-title a:link, #site-title a:visited__text-shadow__vertical" : "1px",
    "#header__#site-title a:link, #site-title a:visited__text-shadow__blur_radius" : "1px",
    "#header__#site-title a:link, #site-title a:visited__text-shadow__color" : "2",
    "body__.entry-title a:link, .entry-title a:visited__text-decoration" : "1",
    "font-family" : "2"
  },
  "Helvetication" :  {
    "color":  "#333333",
    "color__2":  "#7a7a7a",
    "color__3":  "#595959",
    "color__4":  "#c2c2c2",
    "color__5":  "#137fdd",
    "base-font-size":  "16",
    "#header__#site-title a:link, #site-title a:visited__font-size":  "6",
    "font-family":  "15",
    "font-family__2":  "27",
    "#header__#site-title a:link, #site-title a:visited__color":  "3",
    "#header__#site-title a:link, #site-title a:visited__font-family":  "2",
    "#header__#site-title a:link, #site-title a:visited__letter-spacing":  "-.05em",
    "#header__#site-title a:link, #site-title a:visited__font-weight":  "3",
    "body__a:link, a:visited__color":  "3",
    "body__a:link, a:visited__text-decoration":  "1",
    "body__a:hover, a:active__text-decoration":  "2",
    "body__h2__font-family":  "2",
    "body__h2__font-size":  "3",
    "body__h2__font-weight":  "2",
    "body__.widget-title__font-size":  "2",
    "body__.widget-title__font-weight":  "2",
    "body__.widget-title__text-transform":  "2",
    "body__.widget-title__font-family":  "2",
    "#access__a:link, a:visited__color":  "1",
    "#access__a:link, a:visited__font-family":  "2",
    "#access__a:link, a:visited__font-size":  "1",
    "#access__a:link, a:visited__text-transform":  "2",
    "#header__#site-description__margin-top":  "-20px",
    "#header__#site-description__margin-bottom":  "1em",
    "#footer____border-top-color":  "1",
    "#footer____border-top-style":  "5",
    "#footer____border-top-width":  "2px",
    "#header____border-bottom-color":  "1",
    "#header____border-bottom-style":  "5",
    "#header____border-bottom-width":  "2px",
    "body__#breadcrumbs li a, #breadcrumbs li__color":  "4",
    "body__#breadcrumbs li a, #breadcrumbs li__font-family":  "2",
    "body__#breadcrumbs li a, #breadcrumbs li__font-size":  "1",
    "body__#breadcrumbs li a, #breadcrumbs li__text-transform":  "2",
    "body__#breadcrumbs li a, #breadcrumbs li__margin-top":  "24px",
    "body__.page-title, h1__color":  "1",
    "body__.page-title, h1__font-family":  "2",
    "body__.page-title, h1__font-size":  "4",
    "body__.page-title, h1__font-weight":  "2",
    "body__.entry-title a:link, .entry-title a:visited__color":  "1",
    "body__.entry-title a:link, .entry-title a:visited__font-family":  "2",
    "body__.entry-title a:link, .entry-title a:visited__font-size":  "3",
    "#access__ul.sub-menu, ul.sub-menu a:link, ul.sub-menu a:visited__background-color":  "4",
    "#access__a:hover, a:active__color":  "3",
    ".category-galleries__.grid-single h2.gallery-title a__color":  "1",
    ".category-galleries__.grid-single h2.gallery-title a__font-family":  "2",
    ".category-galleries__.grid-single h2.gallery-title a__font-size":  "2",
    ".category-galleries__.grid-single h2.gallery-title a__text-align":  "3",
    ".category-galleries__.grid-single h2.gallery-title a__text-transform":  "2",
    ".category-galleries__div.gallery-icon__text-align":  "3",
    ".category-galleries__div.gallery-icon__box-shadow__horizontal":  "0px",
    ".category-galleries__div.gallery-icon__box-shadow__vertical":  "6px",
    ".category-galleries__div.gallery-icon__box-shadow__blur-radius":  "8px",
    "body__.entry-meta, .entry-meta a:link, .entry-meta a:visited, .entry-utility, .entry-utility a:link, .entry-utility a:visited__font-family":  "2",
    "body__.entry-meta, .entry-meta a:link, .entry-meta a:visited, .entry-utility, .entry-utility a:link, .entry-utility a:visited__font-size":  "1",
    "body__.page-title, h1__letter-spacing":  "-.05em",
    "body____font-family":  "1",
    "body____font-size":  "2",
    ".category-galleries__.grid-single .entry-meta__text-align":  "3",
    ".category-galleries__.grid-single .entry-meta__font-size":  "2",
    ".category-galleries__.grid-single .entry-meta, .grid-single .entry-meta a:link__font-size":  "1",
    ".category-galleries__.grid-single .entry-meta, .grid-single .entry-meta a:link__text-align":  "3",
    "font-size-ratio":  "2",
    "#header__#site-title a:link, #site-title a:visited__margin-top":  "1em",
    "#header__#site-title a:link, #site-title a:visited__margin-bottom":  "1em"
  }
}', true);